provide tide support
lambda-fairy/maud pull request #280
Opened 2021-07-31 21:23 UTC by maxcountryman

This introduces support for Tide by implementing `From` over markup.
Unlike other frameworks, Tide does not seem to provide e.g. a trait
which could instead be implemented. However as demonstrated, this
alternative results in a simple, ergonomic interface.

Consumers may leverage Tide support by using the "tide" feature.

2021-08-01 15:01 UTC, maxcountryman commented
Thanks for looking at this, @lambda-fairy--I think the doctest build should be passing now.

2021-08-04 10:48 UTC, lambda-fairy requested changes
Thanks @maxcountryman!

Can you please add an entry to the changelog as well?

Other than the minor nits, LGTM.

2021-08-04 14:54 UTC, maxcountryman commented on doctest/Cargo.toml
> +async-std = {version = "1.9.0", features = ["attributes"]}
I've instead broken this out; there's a consideration for consistency, but I'll leave that up to you to decide if that's something you want to apply more generally.

2021-08-06 04:21 UTC, lambda-fairy approved these changes
Looks great, thanks!

2021-08-06 04:22 UTC, merged