report error for missing closing tag token
lambda-fairy/maud pull request #287
Opened 2021-08-30 16:38 UTC by emi2k01

![image](https://user-images.githubusercontent.com/78516649/131373451-5e96f8d4-8572-4e93-b471-19b9425055e7.png)

As you can see, I used `abort_call_site` instead of adding a more appropriate span like the rustc one:

![image](https://user-images.githubusercontent.com/78516649/131373583-434c5ffe-4cbc-4328-a1db-57b575d5dfc5.png)

The reason is that I don't know how.

2021-08-30 18:23 UTC, emi2k01 commented
I don't know how to make this a draft. The test failing is named "element-missing-body" but HTML tags are not required to have a body, I think.

Should I rename the test to `non-closed-element`?

2021-09-11 06:55 UTC, lambda-fairy requested changes
Thanks @emi2k01! Happy to merge once the comment is addressed (and the tests pass).

> Should I rename the test to `non-closed-element`?

Sure, do it!

2021-09-11 06:55 UTC, lambda-fairy commented on maud_macros/src/parse.rs
> +            None => abort_call_site!("expected ';' or '/', found end of macro"),
I'd rather only mention `;`, as the `/` syntax is soft-deprecated.

Also, Rust style is to use backticks to delimit code snippets.

```suggestion
            None => abort_call_site!("expected `;`, found end of macro"),
```

2021-09-14 16:58 UTC, emi2k01 commented
Btw, do you know if it's possible to create a diagnostic with whose span is just after the last token? Just like the second screenshot I added to the original comment.

2021-09-18 09:28 UTC, lambda-fairy approved these changes

2021-09-18 09:29 UTC, lambda-fairy commented
Thanks!

> Btw, do you know if it's possible to create a diagnostic with whose span is just after the last token?

There is `Span::after`, but it's unstable.

2021-09-18 09:30 UTC, merged