Add Poem support
lambda-fairy/maud pull request #333
Opened 2022-03-12 20:35 UTC by kitified

Adds support for [Poem](https://docs.rs/poem/latest/poem/) `IntoResponse`.

I didn't add any tests: I didn't see any for `axum`, and this is a similar type-level change.
It also looks like we don't have a great way to test stuff like this in general in the repo right now.

I did test with a local project, attached:
[maud_example.zip](https://github.com/lambda-fairy/maud/files/8238367/maud_example.zip)
.

2022-04-10 09:27 UTC, lambda-fairy requested changes
Thanks for the PR! And sorry for the delay :sweat_smile: 

> I didn't add any tests: I didn't see any for `axum`, and this is a similar type-level change.

Please add a `poem` dependency to the [`doctest` crate](https://github.com/lambda-fairy/maud/blob/main/doctest/Cargo.toml). This will check that the example you added to the docs can be built. (And also fix the CI failure.)

2022-04-10 10:42 UTC, lambda-fairy commented on maud/Cargo.toml
> +poem = { version = "~1", optional = true }
Any particular reason for the `~` dependency? I'd rather avoid these uncommon constructs unless there's a specific reason to use them.

```suggestion
poem = { version = "1.3", optional = true }
```

2022-05-18 21:27 UTC, kitified commented
Actually I've stopped using poem 😶 closing this.

2022-05-18 21:27 UTC, closed without merging

2024-06-24 21:50 UTC, giodamelio commented
I am a current user of poem, and this would be nice so I don't need the wrapper struct.

If I resubmit this as a new PR, would you be open to it @lambda-fairy?